language: python

python:
  - "2.7"
  - "3.5"

before_install:
  - sudo apt-get install -y liblua5.1-dev libmagickwand-dev

install:
  - "pip install pipenv"
  - "pipenv install"

script:
  - pipenv shell
  - py.test --cov tools --cov faf --cov-report term-missing

after_success:
  - coveralls
