language: python

python:
  - "2.7"
  - "3.5"

before_install:
  - sudo apt-get install -y liblua5.1-dev libmagickwand-dev

install:
  - "pip install --upgrade pip"
  - "pip install --trusted-host content.faforever.com -r requirements.txt"
  - "pip install --trusted-host content.faforever.com -r requirements-dev.txt"

script:
  - py.test --cov tools --cov faf --cov-report term-missing

after_success:
  - coveralls
