language: python

python:
  - "3.6"

before_install:
  - sudo apt-get install -y liblua5.1-dev libmagickwand-dev

install:
  - "pip install pipenv"
  - "pipenv install -d"

script:
  - "pipenv run testcov"

after_success:
  - coveralls
